language: node_js
node_js:
- node
before_install:
- pip install --user awscli
script: npm run build
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: www.cloudygoo.com
  region: eu-west-1
  cache_control: max-age=86400
  local_dir: build
  skip_cleanup: true
after_deploy:
- aws cloudfront create-invalidation --distribution-id $CF_DISTRO_ID --paths "/*"
notifications:
  email:
  - "$NOTIFICATION_EMAIL"
  on_success: never
  on_failure: always
env:
  global:
  - secure: BSGjEbTnX/xycvcYX2ro3nPXTlIzy3GD+y0hw4dr+BTOk7OUiiBfq9cRhVUiAtaYtOUCkn8TpGPzHXv3fM/ImY9s+7JMhrRozU/CMcnH68h5bij6A8ymNHJzlxcdBDix76MSr5Z0z2Phw575akNxd8sofnxo2ebc/uIosbzbGeAXjrbYZYIxvO9Lu3E822Rw+zrdD188CEwJsBuISGNaH3Su0NKMvda5zCZMzTXLbsMNpFAq+3CAJhcdzr6HtuRDQjEi6wClxcu/TbFvZ5UP3WIi24zSVzJljz0jcigo+LDETQTz5C2R5fg8bcxvNZSY1zCEZb0ujdbadCllJGR8QtlIzhgoWOHti26fYJ/ruW+FycIJhAMauKtnM0maLURDaIS0iiQ/K3GAvATAOo1uC3VY+oh3nZqt5cJfVFT3RwtIypp6h5D+R2Ax53uMvLEBOxGfaglO6vABAFvoHW1k+HrvxXWLNqrSrj57BRjGQrri33uSj0Bs/J7pxBI6ZgzmCdgLlyCkur4DQP5Rph3/1WYPt/v7i5CN4Lt94FNaNloXeEw2wWPEiU10W0d6sH0c+tnnqKY7wbIBKUkvIS4y1JM6rHV9ASh91vMY/h7ap1YZaXMFd3MT+OodAW1W8a0Qfykuoe6Ll45hkskQFJRUFXRGnruZnEzRyr6lrOvBFZ0=
  - secure: MUetCEI3HC0QY4iXddlhn3+Yy5zTGXhmO8sU6JoE3nqk78g5lLvyyMt7EjdXlC5fwXcW1pcu6mn55lEVAJu7nTbv1+EhOxwnMMpGUTtYF9dkQbX+Y7tfGbTWXZaXO/56GQKnystDoCh5bhwnAqih2g4HyA1U8DE8nvk9bfL89wtzA7E1B7AeyPbBaqTH8xPvYCVyrpdiQMg6mabER71fl89Tdpk2K8d5JGkVVMSaYmDioRnr1lxm8SQzzyorOpTDVCWl6ajF+I5gV6FPCFWiWWeArWLjLKLCoJoSW/Kdw5JRApKg93Se5bUVxPEfgCphxbSPgfiShIflv1RnpYBS1zGyRgnnMSZ1Wh61d5hwCZv7qCdRIsqDksklRcSKgPZpybDhlHQUKdKU2s4oC1il8b2jrDaWBuDIaKI/fNmzxEtTFhNgZuLX3iSr2h4TmmpkpMtUeMjDh75bbpZtCddefKeY24Apdlc8fQbyA8F2wlNSKDxFFc2INEaqc89Q1fNznUaZig+G5edPDSOPH9ENBV12JXokUwmKNBaCogrlq8m8zks4Iv3Yty1RGUzbazdTjDKkqzN1yiCHVkzITRsd1p6ksNxjb/KXWjW50GrpCbmDL+rBRCWIeF4R8tt0jRY51iqA/M57hR2/1kG8NE82E/VF0NOi7NvKMwRZhuv1EDg=
  - secure: AWL+SY8T5CN6Tfg6zUelJ9VINIY1FXTpm2wTfueyPNFY3x63J4Keus0bHyIDNigSiBIAztJS7hUbhgys/QQbblUmtt7VPw2gal6jWzOwNhDMuCmz0Oc+8GuJ1o8pHUmhV0MLTIX7m8P17zctL64T9eMEsBb9Zk9WOKC+YY5Ac99ISWBzkplfMhnsdRX5Zu9y3LYzCCVW2B69EowlsPWT4teirnRCsG6ODBwDXr42AdYM4FDF8/GSOHckbwKb1/qpNXCGdCZPKuiGmqyVv8ZKc5sYcyq3UAAQQVhCh1Uu6aFoVFBKbkwbYD7dLBv47AGOn1xJCiw2T0XpoTigE/lsHCCMTmU/xCSjl7NjctzBBU8Z4w1wcuMn3OYzsQuTmVSYt7MU7yLhFLWAbGZETflniWLGc/qnxbakhLZ8kPQ//uc5AIDZaouxfB8MRaGMDhzklKg4VSltxpTEIxDZpcD8eDLZnogbQxUrZj6FguFz/UVdCwgVdJnlbCjjeRgcVmDFviaz4DSApt9Iw4LjgG3HziH4Oc5vu3/6KXhLpk8ECAjWcxjgnsRj3mPLto3tdq7rMeQi7HlhpuQFcMSsY/yUgoIEXUyXeVu0QTKr2B+j1qTpxjvHUZKR+W/M00FCF14gqF1kK+eNG4UNCjdd7uAaAXAcJiBTz/yn7px9H9384Y0=
  - secure: yGiE2cCwGXCqL3k/lAJ29GPBpVi5tmF2iledojMavL73SwCVpe2U1/F97mh5mBhtCVJi1PKEvLd1wrGRaAHxUWwqxqGlx5gaky1sO01y63TK4ItQUIpb2AAZrIe18oFxJOV/rN8xuhAX7ouKNPQlCB4B1kI+nkrPiMYV9Euln863uNka0VuGKTH04p8OEy3flA/3ch5cxZg6j0z64ThmqGaR/PveVszQcKLA1LONr7XwU2cj/BuJZn+YZTb6z3xjeGvgtXh3/c1ub0WS718INVMyF9sQU4A0kzmj0NoEiNk85FYhe3o+zL8PTJrY9ZWJIl69YPAzoEHDrc/BasHqevaCIy6yv6pxy6t2V0Bk/XSq8GGTwrbbt8Xw9iA00h8ac60Rf5qLmNZJiuqeU6TiQNDL+ChdKaH4vPsLSKZ9tg6ofb8/ldQYjUBuJ+3AD+WBGGH8j6fJspx+eOqMJhB6LT/R2kUt1hZxMmXADGooXFadJQNQ9KskjORtojSwOp+OtHYn9KMoWecMHfcltBVO7n0A/Q36fQ5VKiSvIxKjh5IEXfx4J3wMrB+wj9b3EfCuFGjYCjxxdEu9GAZiy/oDJM//Iip5OgOT/bgddALxLNEBYYXT0ixkQRsFauhMtHARXcRA2CVjyJhGlTrRYNKMo1Az3fOES7HSqAoAqML1VnE=
