language: node_js
node_js:
- node
script: npm run build
deploy:
  on:
    branch: master
  provider: s3
  access_key_id:
    secure: KAH5yP+a6fNCKMokQ33zBn3jbknAFU5sNKb1807qGnYLCHp3JtjrClEU7QaYZ1JEXzAlsZ0BR8kY64/6PPDX6JgYguJNyQT0QtEWOQ2kDlIQl5hYZzQVgKETTHZnVfmvU6KA5jMPGDI31bBxBlD9CLHFrq4O9XzXMMnWvnYfLwwWI18oI0cHw6UGW3yjFCkpj85G9GfzEw2Gjp4ECC5YUMiFYZi/cxII20Na/iO6AKVrHTTHGvju/D6VutulWYz+ojiZ1K+zZ67l5RZ13zSbHy7F3khy5YG/wZJIR8jNsyN9q1+bwLXKOx6fUzghTDRvdU5/Tr2dp9i57E5rpyuK6SqEsokZkIfn4tOTHiokXofqxLjji1We7/zgr9sYwKKHiLFlUBspEJL+nol+lG8b6oiTvMFOKQ4PYW3/S/ix2l88ZXrj9+kwqJ6ptpTTohBm56/sy2USU+soXnGIxgfkP5IFYODqbmx5jjOQTfhWrUBSIoe14w1S9DQInP/f+ee58j2lrU0PGYHhDThiv6vvVu8B3ZdrNWu6XWKcMra43ke16H1fk3VBazQyptCp9YgoQGosWUy9Dw1l7TLxgz6mwmRryMprMl58PTl0kF58dNyZ5/Hp8RQoOFK+msm/sGKzOxfAro1pqGUZdxAOi7wO4VchnvlvbelmAO/Fl82ukgc=
  secret_access_key:
    secure: UT+xhVfas8l2+tAWq9yAqmfSSTUHmV5mFqRFpRG3cMGQvBRS/je8RDwtQs8ItBVOSaeEw39j67ZRklJFSpxRKUmrILUV6YyNXiDIX7ZRuM8345ctuul/OZCgnstfDasBRyl6fupzmC1pRHlqILKqYQNHnfEQ53e2CbupJtsAzg08sYTBLU9b+TzMc9ZPz1jkoPERkh2qfY93Z/pwxwQV3d3oAJ31y125JDzw7/NM6UbXiObNq2+Zrq/KU4Y1T5MwaUOM/76b0EkntB/1JIdsiD/elVfbdS7RB3rhUQtBOAoXaxaF6rWpsnP1QR21iMGTxXJrkcGx4/bUz13k40c8onpN/Q6jYOlLTztgoBvPRFfbwzRaBIvcmAh5uc+zJJfvynHFjcYT4178Sn3FQOqmd3N+UUOjnSrboTEpW8OHA+R7xNFOHNq3lHhzrNjoGRgbM8q7FyAdxcJ+v1vPfp2cJ52ajlyTm+nLxkCn2ACvZz3MIXob9s9lrdiR624sX33pK6f0VQKcI7ay4BGUxSFXeH3pTjAwZatq5UDY4/mc1E4A6TY2e8loSRmYeerccAWXsyJlQRREZE5W/DpC2jno/OXJYLdOBsbe1zzQXEUuJAIfQaneDXyzYlB+9fzRSgAoWMfxrfiMbpqCjRI4yN9SHJZ+eNO1DbdEZqAjUSB1G4Q=
  bucket: www.cloudygoo.com
  region: eu-west-1
  local_dir: build
  acl: public_read
